project:
  type: website

website:
  description: "A blog about reproducible research for newbie Lina"
  title: "Lina's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/linaoa99
format:
  html:
    theme:
      light: morph
    css: styles.css

execute:
  freeze: auto


