project:
  type: website

website:
  description: "A blog about reproducible research for newbie Lina"
  title: "Lina's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/linaoa99
format:
  html:
    theme:
      light: morph
    css: styles.css
    highlight-style: github

execute:
  freeze: auto

sidebar:
  search: true
  style: "docked"
  logo: 
  content:
    - text: "About"
      href: about.qmd
    - text: "Posts"
      menu:
        - text: "How to add a GIF"
          href: posts/gif/index.qmd
        - text: "How to Publish a Quarto Blog via GitHub"
          href: posts/publication/index.qmd
        - text: "How to use Pixi for environment managemen"
          href: posts/pixi/index.qmd
        - text: "How to run Quality Control using Pixi"
          href: posts/pixi_qc/index.qmd


