project:
  type: website

website:
  description: "A blog about reproducible research for newbie Lina"
  title: "Lina's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/linaoa99
  search: 
   location: navbar
  sidebar:
   style: "docked"
   logo: gu_logo.png
   contents:
    - text: "About"
      href: about.qmd
    - section: "Posts"
      href: index.qmd
      contents: 
        - text: "AI in Bioinformatics"
          href: posts/ai/index.qmd
        - text: "Learning ggplot2"
          href: posts/ggplot/index.qmd
        - text: "Pre-made Pipelines in nf-core"
          href: posts/nf_core/index.qmd
        - text: "Basics of Nextflow"
          href: posts/piping/index.qmd
        - text: "How to run Quality Control using Pixi"
          href: posts/pixi_qc/index.qmd
        - text: "Pixi for environment management"
          href: posts/pixi/index.qmd
        - text: "How to Publish a Quarto Blog via GitHub"
          href: posts/publication/index.qmd
        - text: "How to add a GIF"
          href: posts/gif/index.qmd
format:
  html:
    theme: morph
    toc: true
    code-copy: true 
    css: styles.css
    highlight-style: github
    code-overflow: wrap

execute:
  freeze: auto




